import type { EditorThemeClasses } from 'lexical'

/** Theme classes aligned with Mindbase WYSIWYG styles in internal/editor/document.go */
export const mindbaseTheme: EditorThemeClasses = {
  paragraph: 'mb-paragraph',
  heading: {
    h1: 'mb-h1',
    h2: 'mb-h2',
    h3: 'mb-h3',
  },
  quote: 'mb-quote',
  list: {
    ul: 'mb-ul',
    ol: 'mb-ol',
    listitem: 'mb-li',
    listitemChecked: 'mb-li-checked',
    listitemUnchecked: 'mb-li-unchecked',
    checklist: 'mb-checklist',
    nested: {
      listitem: 'mb-li-nested',
    },
  },
  code: 'mb-code-block',
  codeHighlight: {
    atrule: 'mb-token',
    attr: 'mb-token',
    boolean: 'mb-token',
    builtin: 'mb-token',
    cdata: 'mb-token',
    char: 'mb-token',
    class: 'mb-token',
    'class-name': 'mb-token',
    comment: 'mb-token-comment',
    constant: 'mb-token',
    deleted: 'mb-token',
    doctype: 'mb-token',
    entity: 'mb-token',
    function: 'mb-token',
    important: 'mb-token',
    inserted: 'mb-token',
    keyword: 'mb-token',
    namespace: 'mb-token',
    number: 'mb-token',
    operator: 'mb-token',
    prolog: 'mb-token',
    property: 'mb-token',
    punctuation: 'mb-token',
    regex: 'mb-token',
    selector: 'mb-token',
    string: 'mb-token',
    symbol: 'mb-token',
    tag: 'mb-token',
    url: 'mb-token',
    variable: 'mb-token',
  },
  link: 'mb-link',
  text: {
    bold: 'mb-bold',
    italic: 'mb-italic',
    code: 'mb-inline-code',
    strikethrough: 'mb-strike',
    underline: 'mb-underline',
  },
}
